# Generated by Django 5.2.4 on 2025-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_building_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='facility',
        ),
        migrations.AddField(
            model_name='building',
            name='facilities',
            field=models.ManyToManyField(to='mainapp.facility'),
        ),
    ]
