# Generated by Django 5.2.4 on 2025-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_facility_remove_building_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/'),
        ),
    ]
