# Generated by Django 5.2.4 on 2025-08-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_building_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='img',
            new_name='thumbnail',
        ),
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='', verbose_name='building_images/')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_images', to='mainapp.building')),
            ],
        ),
    ]
