# Generated by Django 5.2.4 on 2025-08-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_img_building_thumbnail_buildingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='facilities',
            field=models.ManyToManyField(related_name='building_facilities', to='mainapp.facility'),
        ),
    ]
