# Generated by Django 5.2.4 on 2025-08-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_building_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='deposite',
            new_name='deposit',
        ),
    ]
