# Generated by Django 5.2.4 on 2025-08-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_deposite_building_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimage',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_images', to='mainapp.building'),
        ),
    ]
